### ISSUE TITLE
Nome da cidade de São José do Vale do Rio Preto - RJ

### ISSUE THREAD

**Issue by fabiothz** [felipefdl/cidades-estados-brasil-json#3]
Agora que encontrei estes dados, não vou te dar paz, rsrs
Brincadeiras... Obrigado por compartilhar estas informações...

Vi agora outro detalhes, falta a última letra do nome desta cidade:

 ```
{
	"ID": "3667",
	"Nome": "São José do Vale do Rio Pret",
	"Estado": "19"
}
```

**Comment by felipefdl** [comment]
@fabiothz  voce pode estar enviando o Pull Request com as modificações.

**Comment by fabiothz** [comment]
Blz!
